### ISSUE TITLE
Task 4: Create a tergmLite version of the network_update module function

### ISSUE THREAD

**Issue by andsv2** [statnet/EpiModel#333]
### Goals
 -  tergmLite is used for network simulation, this version of the module would replace the tergm/networkDynamic version for more efficient simulation 
 - Main speed improvements with edgelist-only version of add and delete vertices 

### TODO
- [x] Port functionality from EpiModelHIV 
- [x] Address all remaining errors in R CMD Check
- [x] Consolidate init_status functions
- [x] Check/edit init module
- [x] Check/edit infection module
- [x] Check/edit resim_nets
- [x] Check/edit nwupdate.net
- [x] Rename prevalence module
- [x] Rename nw.update.net module/fx
- [x] Rename 2 group functions to X.2g.net
- [x] Change storage location for `nwupdate.net` from `dat$nw.update...` to `dat$temp...`; and decide which of these are necessary (versus on-the-fly queries)
- [x] Rename `depend` control setting. `resimulate.network`?
- [x] Figure out what to do with persistent IDs (#307, #341); also, PIDs are not getting updated (at least for 2g models)
- [x] Start on unit testing
- [x] Move new nodal attr updates to `dat$attr` from `nwupdates.net` to `arrivals.net`
- [x] Change variable name `bip`, with T/F value, in crosscheck to nGroups, with 1/2 value
- [x] Simplify copying attr back/forth from dat$attr to nw: instead of limiting it to only terms on the ergm formula, do it for all attributes originally passed on the network
- [x] Test/adapt serosorting (statOnNw) model for tergmLite
- [x] Remove duplicate setting of dat$attr code in arrivals.net; we should not need to look up based on use of tergmLite
- [x] Address hard-coding of group numbers to 2, like this `length(unique(get.vertex.attribute(nw, "group")))`
- [x] Address cases where group is on the nw as an attribute but not in the ergm formula; and also address cases where other attributes (race, age) are passed in on the network but not on the ergm formula. 
- [x] `tergmLite` replaces save.network and save.transmat. If FALSE, then save these two things. If TRUE, don't save them.
- [x] Check on why the calls to `test_net` in test-net-long unit test script are failing on R devel
- [x] merge.netsim doc issue (#342); although if save.network is removed, the fix is different
- [x] Add unit tests with attribute copying based on examples at the end of the EpiModel test script

**Comment by smjenness** [comment]
@andsv2 Running your test scripts, this still does not work with netsim:

```r

num <- 200
nw <- network::network.initialize(num, directed = FALSE)
formation <- ~ edges
target.stats <- 60
coef.diss <- dissolution_coefs(dissolution = ~ offset(edges), duration = 50)
est <- netest(nw, formation, target.stats, coef.diss)

# Parameters
init <- init.net(i.num = 10)
param <- param.net(inf.prob = 0.1, act.rate = 5)
control <- control.net(type = "SI", nsteps = 100, nsims = 5, tgl = TRUE,
                       save.nwstats = FALSE)

sim <- netsim(est, param, init, control)
```

with the error:

```r
> sim <- netsim(est, param, init, control)

Starting Network Simulation...Error in UseMethod("simulate") : 
  no applicable method for 'simulate' applied to an object of class "list"
```

**Comment by smjenness** [comment]
This is done! Woo-hoo!
