### ISSUE TITLE
CRAN Release Checklist: EpiModel v2.0.3

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#464]
**Before publishing on CRAN** 🔨 
- [x] _SKIP:_ Run code coverage analysis using `library("covr"); report(package_coverage())`
- [x] Delint package with `lintr::lint_package`. Can ignore snake case variable warnings. 
- [x] Run tests on linux, windows, and mac using `rhub::check_for_cran(show_status = FALSE)`
- [x] Update version and date on `EpiModel-package.R` file and DESCRIPTION
- [x] Update NEWS
- [x] Build source package
- [x] Tag release
- [x] Upload to CRAN

**After published on CRAN** 💅 
- [x] Update README: badges, v#, DOI
- [x] If necessary: Update tutorials for any major changes
- [x] Updates to http://epimodel.org/
- [x] If necessary: redeploy shiny apps to http://statnet.shinyapps.io/
- [x] Optional: Announce new version on twitter; Email listserv with changes
- [x] Create new release milestone
- [x] Create new release CRAN checklist issue
- [x] Close current issue milestone and checklist issue

**Comment by smjenness** [comment]
Check NME examples specifically for issues #452 and #453 and #451
