### ISSUE TITLE
CRAN Release Checklist: EpiModel v2.0.6

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#527]
**Periodically (not every release)** 📆 
- [ ] _SKIP:_ Run code coverage analysis using `library("covr"); report(package_coverage())`
- [ ] Delint package with `lintr::lint_package`. Can ignore snake case variable warnings. 

**Before publishing on CRAN** 🔨 
- [ ] _SKIP:_ Run code coverage analysis using `library("covr"); report(package_coverage())`
- [ ] Delint package with `lintr::lint_package`. Can ignore snake case variable warnings. 
- [ ] Run tests on linux, windows, and mac using `rhub::check_for_cran(show_status = FALSE)`
- [ ] Update version and date on `EpiModel-package.R` file and DESCRIPTION
- [ ] Update NEWS
- [ ] Build source package
- [ ] Tag release
- [x] Upload to CRAN

**After published on CRAN** 💅 
- [ ] Update README: badges, v#, DOI
- [ ] If necessary: Update tutorials for any major changes
- [ ] Updates to http://epimodel.org/
- [ ] If necessary: redeploy shiny apps to http://statnet.shinyapps.io/
- [ ] Optional: Announce new version on twitter
- [ ] Create new release milestone
- [ ] Create new release CRAN checklist issue
- [ ] Close current issue milestone and checklist issue
