### ISSUE TITLE
Checklist for CRAN release

### ISSUE THREAD

**Issue by smjenness** [statnet/EpiModel#78]
**Before publishing on CRAN** 🔨 
- [ ] Run code coverage analysis using `library("covr"); report(package_coverage())`
- [ ] Run tests on linux, windows, and mac using `rhub::check_for_cran(show_status = FALSE)`
- [ ] Update version and date on `EpiModel-package.R` file and DESCRIPTION
- [ ] Update NEWS
- [ ] Build source package
- [ ] Tag release
- [ ] Close issue milestone
- [ ] Upload to CRAN

**After published on CRAN** 💅 
- [ ] Update README: badges, v#, DOI
- [ ] If necessary: Update tutorials for any major changes
- [ ] Updates to http://epimodel.org/
- [ ] If necessary: redeploy shiny apps to http://statnet.shinyapps.io/
- [ ] Optional: Announce new version on twitter; Email listserv with changes
- [ ] Bump this checklist to next milestone and close milestone

**Comment by andsv2** [comment]
I tried to run devtools::check_rhub() and get this error: "‘samuel.m.jenness@emory.edu’ is not validated, or does not match the package maintainer's email. To validate it now, please enter the email address below. Note that r-hub will send a token to this address."

**Comment by smjenness** [comment]
Closing this general one, moving to a version-specific checklist.
